name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  build:
    name: Build and push job
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "11.0.7"
          architecture: x64
      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Push to GitHub Docker Registry
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: Nordstrom/zkr
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
