name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  build:
    name: Build and push job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Check out code

      - uses: actions/setup-java@v1
        name: Set up JDK
        with:
          java-version: '11.0.7'
          architecture: x64
      - name: Build with Gradle
        run: ./gradlew shadowJar

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build and push image to GitHub Container Registry
        with:
          image: Nordstrom/zkr
          registry: ghcr.io
          githubOrg: Nordstrom
          # username: ${{ github.actor }}
          # password: ${{ github.token }}
