name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  build:
    name: Build and push job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        name: Check out code

      - uses: crazy-max/ghaction-docker-meta@v1
        name: Docker meta
        id: docker_meta
        with:
          images: Nordstrom/zkr

      - uses: actions/setup-java@v1
        name: Set up JDK
        with:
          java-version: "11.0.7"
          architecture: x64
      - name: Build with Gradle
        run: ./gradlew shadowJar

      - uses: docker/login-action@v1
        name: Login to Github Container Registry
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: docker/build-push-action@v2
        name: Build and push image
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
